// Generated by CoffeeScript 1.12.7
(function() {
  var DEFAULT, debugElementIds;

  DEFAULT = false;

  debugElementIds = ["meta-detected-frequency", "meta-note", "meta-cents-out"];

  window.setDebug = function(mode) {
    if (mode) {
      debugOn();
    } else {
      debugOff();
    }
    return null;
  };

  window.debugOn = function() {
    var i, j, len;
    for (j = 0, len = debugElementIds.length; j < len; j++) {
      i = debugElementIds[j];
      $("#" + i).removeClass("hidden");
    }
    return null;
  };

  window.debugOff = function() {
    var i, j, len;
    for (j = 0, len = debugElementIds.length; j < len; j++) {
      i = debugElementIds[j];
      $("#" + i).addClass("hidden");
    }
    return null;
  };

  setDebug(DEFAULT);

}).call(this);
