// Generated by CoffeeScript 1.12.7
(function() {
  var DEFAULT, debugElementIds;

  DEFAULT = false;

  debugElementIds = ["meta-detected-frequency", "meta-note", "meta-cents-out"];

  window.setDebug = function(mode) {
    if (mode) {
      debugOn();
    } else {
      debugOff();
    }
    return null;
  };

  window.debugOn = function() {
    var i, j, ref;
    for (i = j = 0, ref = debugElementIds.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      $("#" + debugElementIds[i]).removeClass("hidden");
    }
    return null;
  };

  window.debugOff = function() {
    var i, j, ref;
    for (i = j = 0, ref = debugElementIds.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      $("#" + debugElementIds[i]).addClass("hidden");
    }
    return null;
  };

  setDebug(DEFAULT);

}).call(this);
