// Generated by CoffeeScript 1.12.7
(function() {
  var METRONOME_INCREMENT, click, metLoop, metSpeedField, metronomeIsOn, playMetClick, updateMetronome;

  METRONOME_INCREMENT = 5;

  metSpeedField = $("#metronome-bpm");

  click = new Audio("met_click.wav");

  metronomeIsOn = false;

  $("#metronome-toggle-button").click(function() {
    if (metronomeIsOn) {
      $(this).text("Start");
    } else {
      $(this).text("Stop");
    }
    metronomeIsOn = !metronomeIsOn;
    return updateMetronome();
  });

  $("#metronome-up-button").click(function() {
    metSpeedField.val(parseInt(metSpeedField.val()) + METRONOME_INCREMENT);
    return metSpeedField.change();
  });

  $("#metronome-down-button").click(function() {
    metSpeedField.val(parseInt(metSpeedField.val()) - METRONOME_INCREMENT);
    return metSpeedField.change();
  });

  metSpeedField.change(function() {
    return updateMetronome();
  });

  metLoop = null;

  updateMetronome = function() {
    var bpm;
    bpm = metSpeedField.val();
    clearInterval(metLoop);
    if (metronomeIsOn) {
      playMetClick();
      return metLoop = setInterval(playMetClick, 1000 * 60 / bpm);
    }
  };

  playMetClick = function() {
    return click.play();
  };

}).call(this);
